// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4J6chRbuGZATzR6iDJvs8Il5Pr1eE4-8',
    appId: '1:511849249089:web:adfb87cc0ed7e4735949c0',
    messagingSenderId: '511849249089',
    projectId: 'doctor-appointment-front',
    authDomain: 'doctor-appointment-front.firebaseapp.com',
    storageBucket: 'doctor-appointment-front.firebasestorage.app',
    measurementId: 'G-2C8HX1Y119',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh1zYdKSN9TVDmOY1KPDbD6WvhNrSR_iE',
    appId: '1:511849249089:android:e25abd58ef963dc75949c0',
    messagingSenderId: '511849249089',
    projectId: 'doctor-appointment-front',
    storageBucket: 'doctor-appointment-front.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoFoRZ2hfVWya1sEhuyDA32FNg6aMK-p8',
    appId: '1:511849249089:ios:d55e9b0424e997165949c0',
    messagingSenderId: '511849249089',
    projectId: 'doctor-appointment-front',
    storageBucket: 'doctor-appointment-front.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoFoRZ2hfVWya1sEhuyDA32FNg6aMK-p8',
    appId: '1:511849249089:ios:d55e9b0424e997165949c0',
    messagingSenderId: '511849249089',
    projectId: 'doctor-appointment-front',
    storageBucket: 'doctor-appointment-front.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4J6chRbuGZATzR6iDJvs8Il5Pr1eE4-8',
    appId: '1:511849249089:web:d16beef266a0b3095949c0',
    messagingSenderId: '511849249089',
    projectId: 'doctor-appointment-front',
    authDomain: 'doctor-appointment-front.firebaseapp.com',
    storageBucket: 'doctor-appointment-front.firebasestorage.app',
    measurementId: 'G-04YC1J23EF',
  );
}
